# fly.toml app configuration file generated for weathered-violet-9994 on 2023-09-21T11:24:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-violet-9994"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
