application:
  host: 127.0.0.1
database:
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@yandex.ru"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000